In [1]:
from sklearn.linear_model import LinearRegression

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv('advertising.csv')

In [4]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [5]:
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [6]:
model = LinearRegression()

In [10]:
model.fit(df.drop('Sales', axis=1), df.Sales)

LinearRegression()

In [12]:
model.coef_

array([0.05444578, 0.10700123, 0.00033566])

In [13]:
df.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [14]:
pr = model.predict(df.drop('Sales',axis=1))
pr

array([21.22097209, 11.26824775, 10.49620897, 17.31244651, 15.64413685,
       10.35633677, 11.2732847 , 13.27062458,  5.31839603, 15.78871013,
        8.8527202 , 18.88400523,  9.69879662, 10.74921373, 19.27328852,
       20.38554445, 12.27105794, 24.20214502, 10.5924398 , 15.20872794,
       19.49794066, 18.10414656,  7.06177654, 18.87221072,  9.37145421,
       19.31996936, 15.54479137, 19.49216302, 21.07865408, 10.19471067,
       23.61492832, 12.64683045, 10.08782551, 21.2260486 ,  9.98787085,
       20.89407055, 23.84503494, 13.99342411,  9.8404516 , 21.08344935,
       18.04712878, 17.84885818, 23.57494339, 16.79762772,  8.75617872,
       16.57668108, 10.58020572, 22.13342743, 18.70257411,  9.53181337,
       15.84670856, 11.11990058, 20.88243422, 19.53008343, 22.01500291,
       20.76038994,  8.04320903, 14.10063486, 21.4222098 , 19.25650785,
        7.75915886, 23.43911942, 19.32168181, 13.3867616 , 16.35231896,
        9.37729644,  8.97313482, 13.7643628 , 20.49677834, 21.13

In [29]:
from sklearn.metrics import r2_score,mean_squared_error
from math import sqrt
print("R2_score: {}\nMSE: {}\nRMSE: {}".format(r2_score(list(df['Sales']), list(pr)),
mean_squared_error(list(df['Sales']), list(pr)),sqrt(mean_squared_error(list(df['Sales']), list(pr)))))

R2_score: 0.9025912899684558
MSE: 2.706006147627315
RMSE: 1.6449942697855562


In [30]:
model.coef_

array([0.05444578, 0.10700123, 0.00033566])

In [55]:
print('%.6f'% (model.predict([[0,0,0]])[0]))
print('%.6f'% (model.predict([[1,0,0]])[0]-model.predict([[0,0,0]])))
print('%.6f'% (model.predict([[0,1,0]])[0]-model.predict([[0,0,0]])))
print('%.6f'% (model.predict([[0,0,1]])[0]-model.predict([[0,0,0]])))

4.625124
0.054446
0.107001
0.000336


In [54]:
462512407
5444578
10700122
33565 

33565